#
# v1.0, Michael Wuertenberger
#
name: setup test
description: downlad package install and install testenvironment

runs:
  using: 'composite'
  steps:
    - name: download dist
      uses: actions/download-artifact@v2
      with:
        name: dist
        path: dist
    
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: install #1
      run: python -m pip install cython wheel
      shell: bash
    
    - name: install #2
      run: python -m pip install dist/mountwizzard4.tar.gz
      shell: bash
    
    - name: install #3
      run: python -m pip install pytest==4.6.11
      shell: bash
    
    - name: install #4
      run: python -m pip install pytest-qt
      shell: bash
    
    - name: install #5
      run: python -m pip install pytest-pythonpath
      shell: bash
