#
# v1.0, Michael Wuertenberger
#
name: setup test
description: downlad package install and install testenvironment

defaults:
  run:
    shell: bash

runs:
  using: 'composite'
  steps:
    - name: download dist
      uses: actions/download-artifact@v2
      with:
        name: dist
        path: dist
    
    - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
    
    - name: install package
      run: |
        python -m pip install cython wheel
        python -m pip install dist/mountwizzard4.tar.gz

    - name: install pytest
      run: |
        python -m pip install pytest
        python -m pip install pytest-qt
        python -m pip install pytest-pythonpath
