#
# GitHub actions for running the unit test of the mountwizzard4 package
#
# v1.0, Michael Wuertenberger
#
name: setup test coverage
description: download package install and install testenvironment for coverage
author: Michael Würtenberger

runs:
  using: 'composite'
  steps:
    - uses: actions/download-artifact@v2
      with:
        name: dist
        path: dist
        
    - name: install_package
      run: |
        python -m pip install cython wheel
        python -m pip install dist/mountwizzard4.tar.gz
        python -m pip install comtypes==1.1.7

    - name: install_pytest
      run: |
          python -m pip install pytest==4.6.11
          python -m pip install pytest-qt
          python -m pip install pytest-cov
          python -m pip install pytest-pythonpath