path_classifiers:
    - mw4/
    - exclude: mw4/resource/
    - exclude: mw4/gui/widgets/
    - exclude: setup.py
    - exclude: tasks.py
    - exclude: py/similar-function
    - exclude: test/
  test:
    - test/ 

