#
# v1.0, Michael Wuertenberger
#
name: setup test coverage
description: download package install and install testenvironment for coverage

runs:
  using: 'composite'
  steps:
    - name: download dist
      uses: actions/download-artifact@v2
      with:
        name: dist
        path: dist
        
    - name: install package
      run: |
        python -m pip install cython wheel
        python -m pip install dist/mountwizzard4.tar.gz
        python -m pip install comtypes==1.1.7
      shell: bash

    - name: install pytest
      run: |
          python -m pip install pytest==4.6.11
          python -m pip install pytest-qt
          python -m pip install pytest-cov
          python -m pip install pytest-pythonpath
      shell: bash