#
# GitHub actions for running the unit test of the mountwizzard4 package
#
# v1.0, Michael Wuertenberger
#
name: build_package
description: build package and uploads as artifact

runs:
  using: 'composite'
  
  steps:
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: install package
      shell: bash
      run: |
        python -m pip install setuptools wheel
        python setup.py sdist
        mv dist/mountwizzard4*.* dist/mountwizzard4.tar.gz

    - name: upload_package
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist