name: Build Wheels
author: michael wuertenberger

on:
  push:
    paths:
      - 'setup.py'
      - '.github/workflows/build_python_win_wheels.yml'

jobs:
  building_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        python-version: [3.7, 3.8, 3.9]

    steps:
      - name: checkout_${{ matrix.python-version }}_${{ matrix.os }}
        uses: actions/checkout@v2

      - name: Setup_Python_${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: build_wheels
        run: |
          python -m pip install wheel
          python -m pip install cython
          python -m pip wheel sep -w wheelhouse

      - name: upload_wheels
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: wheelhouse

  bollecting_push_wheels:
    runs-on: [ubuntu-latest]
    needs: building_wheels
    steps:
      - name: collect_wheels
        uses: actions/download-artifact@v2
        with:
          name: wheels
          path: wheelhouse

      - name: commit_repo
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull
          git add wheelhouse/sep*.*
          git commit -m "Using WHL" -a

      - name: push_changes_repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}