#
# GitHub actions for running the unit test of the mountwizzard4 package
#
# v1.0, Michael Wuertenberger
#
- name: install_package_test

runs:
  using 'composite'
  steps:
    - uses: actions/download-artifact@v2
      with:
        name: dist
        path: dist
    
    - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
    
    - name: install_package
      run: |
        python -m pip install cython wheel
        python -m pip install dist/mountwizzard4.tar.gz

    - name: install_pytest
      run: |
        python -m pip install pytest
        python -m pip install pytest-qt
        python -m pip install pytest-pythonpath