#
# GitHub actions for checking the installation of mountwizzard4 packages
#
# v0.1, Michael Wuertenberger
#
name: install_script_test
env:
  gh: 'https://raw.githubusercontent.com/mworion/MountWizzard4/master/support/2.0/'

on:
  push:
    # Run this action on the trigger event when specific files are touched
    paths:
      - '.github/workflows/install_script_test.yml'
      - 'support/**'

jobs:
  
  install_windows:
    
    # downloads the packages from job 1, installs all necessary items for being
    # able to run the installation with the test scripts and finally run mw4 for
    # some seconds
  
    runs-on: windows-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install Script Install
        uses: suisei-cn/actions-download-file@v1
        with:
          url: ${{ env.gh }}Windows/MW4_Install.bat
          target: .
      
      - name: Install Script Run
        uses: suisei-cn/actions-download-file@v1
        with:
          url: ${{ env.gh }}Windows/MW4_Run.bat
          target: .
      
      - name: MountWizzard4 Install
        shell: cmd
        run: |
          call MW4_Install.bat
          more install.log
      
      - name: Run MountWizzard4
        shell: cmd
        run: |
          touch test.txt
          call MW4_Run.bat
          dir
          more run.log
  
  install_ubuntu:
    
    # downloads the packages from job 1, installs all necessary items for being
    # able to run the installation with the test scripts and finally run mw4 for
    # some seconds
  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install Head
        run: |
          sudo apt-get update
          sudo apt-get -y upgrade
          sudo apt-get install -y xvfb libxkbcommon-x11-0 x11-utils libxcb-icccm4
          sudo apt-get install -y libxcb-image0 libxcb-keysyms1 libxcb-randr0
          sudo apt-get install -y libxcb-render-util0 libpulse-mainloop-glib0
          sudo apt-get install -y libx11-xcb1 libxcb-xinerama0 libxcb-xkb1
          sudo apt-get install -y libxcb-keysyms1
        
      - name: Install Script Install
        uses: suisei-cn/actions-download-file@v1
        with:
          url: ${{ env.gh }}Ubuntu/MW4_InstallTest.sh
          target: .

      - name: Install Script Run
        uses: suisei-cn/actions-download-file@v1
        with:
          url: ${{ env.gh }}Ubuntu/MW4_Run.sh
          target: .
          
      - name: MountWizzard4 Install
        run: |
          chmod 777 MW4_Install.sh
          ./MW4_Install.sh
          cat install.log
          
      - name: Run MountWizzard4
        run: |
          touch test.txt
          chmod 777 MW4_Run.sh
          xvfb-run ./MW4_Run.sh
          ls -la
          cat run.log
          
  install_macOS:
    
    # downloads the packages from job 1, installs all necessary items for being
    # able to run the installation with the test scripts and finally run mw4 for
    # some seconds
  
    runs-on: macos-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Script Install
        uses: suisei-cn/actions-download-file@v1
        with:
          url: ${{ env.gh }}MacOSx/MW4_Install.command
          target: .

      - name: Install Script Run
        uses: suisei-cn/actions-download-file@v1
        with:
          url: ${{ env.gh }}MacOSx/MW4_Run.command
          target: .
          
      - name: MountWizzard4 Install
        run: |
          chmod 777 MW4_Install.command
          ./MW4_InstallTest.command
          cat install.log
          
      - name: Run MountWizzard4
        run: |
          chmod 777 MW4_Run.command
          touch test.txt
          ./MW4_Run.command
          ls -la
          cat run.log
 
