name: Python3.7 Ubuntu

on:
  push:
    paths:
      - 'mw4/**'
      - 'README.rst'
      - 'setup.py'
      - '.github/workflows/python3.7_ubuntu.yml'

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build widgets and resource
      run: |
        python -m pip install --upgrade pip
        python -m pip install PyQt5
        python -m PyQt5.pyrcc_main mw4/resource/resources.qrc -o mw4/resource/resources.py
        python -m pip install pyqt5ac
        python -m pyqt5ac --config compile.yml

    - name: Build package
      run: |
        pip install setuptools wheel
        python setup.py sdist

    - name: Install package
      run: |
        python -m pip install dist/mountwizzard*.tar.gz

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8
