#
# GitHub actions
#
# v0.1,  Michael Wuertenberger
#
name: rpi4_stellarmate64

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

on:
  push:
    # Run this action on the trigger event when specific files are touched
    paths:
      - '.github/workflows/rpi4_stellarmate64.yml'
      - 'support/2.0/StellarMate64/MW4_Install.sh'

jobs:
  install_job:
    # The host should always be linux
    runs-on: ubuntu-20.04
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    # Run steps on a matrix of 3 arch/distro combinations
    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu20.04

    steps:
      - uses: uraimo/run-on-arch-action@v2.1.1
        name: build_artifact
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}

          # Not required, but speeds up builds
          githubToken: ${{ github.token }}

          # Create an artifacts directory
          setup: |
            mkdir -p "${PWD}/artifacts"

          # Mount the artifacts directory as /artifacts in the container
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"
            --platform linux/arm64/v8

          # Pass some environment variables to the container
          env: | # YAML, but pipe character is necessary
            artifact_name: git-${{ matrix.distro }}_${{ matrix.arch }}

          # The shell to run commands with in the container
          shell: /bin/bash

          # Install some dependencies in the container. This speeds up builds if
          # you are also using githubToken. Any dependencies installed here will
          # be part of the container image that gets cached, so subsequent
          # builds don't have to re-install them. The image layer is cached
          # publicly in your project's package repository, so it is vital that
          # no secrets are present in the container state or logs.
          
          install: |
            apt-get update -y
            apt-get upgrade -y
            apt-get install -y software-properties-common
            add-apt-repository ppa:deadsnakes/ppa
            apt-get update -y
            apt-get -y install python3.8 python3-pip python3.8-venv
            apt-get -y install wget
          
          # Produce a binary artifact and place it in the mounted volume
          run: |
            GITHUB="https://github.com/mworion/MountWizzard4/blob/master"
            SCRIPT="/support/2.0/StellarMate64"
            wget "${GITHUB}${SCRIPT}/MW4_Install.sh"
            chmod 777 MW4_Install.sh
            ./MW4_Install.sh
