#
# GitHub actions for checking the installation of MW4 through scripts
#
# v 1.0, Michael Wuertenberger
#
name: test_scripts_pypi_raspi

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  gh: 'https://raw.githubusercontent.com/mworion/MountWizzard4/master/support/3.0/'

on:
  push:
    # Run this action on the trigger event when specific files are touched
    paths:
      - '.github/workflows/test_scripts_pypi_raspi.yml'
      - 'support/**'
      - 'setup.py'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [aarch64]
        include:
        - arch: aarch64
          cpu: cortex-a53
          base_image: raspios_lite_arm64:latest
          cpu_info: raspberrypi_zero2_w_arm64_w

    steps:
      - uses: actions/checkout@v3.3.0
      - uses: pguyot/arm-runner-action@v2
        with:
          base_image: ${{ matrix.base_image }}
          cpu: ${{ matrix.cpu }}
          cpu_info: ${{ matrix.cpu_info }}
          commands: |
            python3 --version
            cd /root/support/3.0
            cd ../wheels
            ls -la
            python3 -m venv venv
            source ./venv/bin/activate
            pip list
            pacman -h
            pacman -F python-pyqt5-sip-12.11.1-1-aarch64.pkg.tar.xz
            pacman -F python-pyqt5-5.15.9-1-aarch64.pkg.tar.xz
            pip install mountwizzard4==3.0.1a0
            cat ./log/mw4*.log
            ls -la
