#
# GitHub actions for running the unit test of the mountwizzard4 package
#
# v0.1, Michael Wuertenberger
#
name: test

on:
  push:
    # Run this action on the trigger event when specific files are touched
    paths:
      - '.github/workflows/test.yml'

jobs:
  find:
    runs-on: [windows-latest]
    
    steps:
      - name: find dll
        shell: cmd
        run: |
          dir c:\Windows\System32\UI*.dll
          dir c:\Windows\SysWOW64\UI*.dll
  