#
# GitHub actions for running the unit test of the mountwizzard4 package
#
# v0.1, Michael Wuertenberger
#
name: test

on:
  push:
    # Run this action on the trigger event when specific files are touched
    paths:
      - '.github/workflows/test.yml'

jobs:
  find:
    runs-on: [windows-latest]
    
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
            
      - name: find dll
        shell: cmd
        run: |
          dir c:\Windows\System32\UI*.dll
          dir c:\Windows\SysWOW64\UI*.dll
          echo %PATH%
          echo %PAYTHONPATH%

      - name: test python path
        run: |
          python -c 'import sys; print(sys.path)'
          python -m pip install pywinauto
          python -c 'import sys; sys.path.insert(0, 'c:/Windows/System32'); import pywinauto.timings'