#
# GitHub actions for running the unit test of the mountwizzard4 package
#
# v1.0, Michael Wuertenberger
#
name: unit_macOS

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  wid: 'mw4/gui/widgets/'
  uic: 'python -m PyQt5.uic.pyuic'
  ucc: 'python -m PyQt5.pyrcc_main'
  res: 'mw4/resource/'
  branch: 'master'
  
on:
  push:
    # Run this action on the trigger event when specific files are touched
    paths:
      - 'mw4/**'
      - 'tests/unit_tests/**'
      - 'setup.py'
      - '.github/workflows/unit_macOS.yml'

jobs:
  build_widgets_resource:
    #
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{env.branch}}
          
      - name: build package
        uses: ./.github/actions/build_package

  run_tests_macos_1:
    #
    needs: build_widgets_resource
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{env.branch}}
  
      - name: install package
        uses: ./.github/actions/setup_test
  
      - name: running_unit_tests
        run: |
          pytest tests/unit_tests/zLoader
          pytest tests/unit_tests/zUpdate
          pytest tests/unit_tests/zMainApp
          pytest tests/unit_tests/gui/mainWindow

  run_tests_macos_2:
    #
    needs: build_widgets_resource
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{env.branch}}
  
      - name: install package
        uses: ./.github/actions/setup_test

      - name: running_unit_tests
        run: |
          pytest tests/unit_tests/base
          pytest tests/unit_tests/logic
          pytest tests/unit_tests/mountcontrol
          pytest tests/unit_tests/indibase
          pytest tests/unit_tests/gui/utilities
          pytest tests/unit_tests/gui/extWindows

  run_tests_macos_3:
    #
    needs: build_widgets_resource
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{env.branch}}
  
      - name: install package
        uses: ./.github/actions/setup_test
  
      - name: running_unit_tests
        run: |
          pytest tests/unit_tests/gui/mainWmixin
