#
# v1.0, Michael Wuertenberger
#
name: unit_ubuntu
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  wid: 'mw4/gui/widgets/'
  uic: 'python -m PyQt5.uic.pyuic'
  ucc: 'python -m PyQt5.pyrcc_main'
  res: 'mw4/resource/'
  branch: 'master'

on:
  push:
    # Run this action on the trigger event when specific files are touched
    paths:
      - 'mw4/**'
      - 'tests/unit_tests/**'
      - 'setup.py'
      - '.github/workflows/unit_ubuntu.yml'

jobs:
  build_widgets_resource:
    #
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{env.branch}}
          
      - name: build package
        uses: ./.github/actions/build_package
        
  run_tests_ubuntu_1:
    #
    needs: build_widgets_resource
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{env.branch}}
    
      - name: install package
        uses: ./.github/actions/setup_test
    
      - name: install head
        uses: ./.github/actions/install_ubuntu_head

      - name: running_unit_tests
        run: |
          xvfb-run pytest tests/unit_tests/base
          xvfb-run pytest tests/unit_tests/logic
          xvfb-run pytest tests/unit_tests/mountcontrol
          xvfb-run pytest tests/unit_tests/indibase
          xvfb-run pytest tests/unit_tests/gui/utilities
          xvfb-run pytest tests/unit_tests/gui/extWindows
        
  run_tests_ubuntu_2:
    #
    needs: build_widgets_resource
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{env.branch}}
    
      - name: install package
        uses: ./.github/actions/setup_test
    
      - name: install head
        uses: ./.github/actions/install_ubuntu_head
  
      - name: running_unit_tests
        run: |
          xvfb-run pytest tests/unit_tests/zLoader
          xvfb-run pytest tests/unit_tests/zUpdate
          xvfb-run pytest tests/unit_tests/zMainApp
          xvfb-run pytest tests/unit_tests/gui/mainWindow


  run_tests_ubuntu_3:
    #
    needs: build_widgets_resource
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{env.branch}}
    
      - name: install package
        uses: ./.github/actions/setup_test
    
      - name: install head
        uses: ./.github/actions/install_ubuntu_head
  
      - name: running_unit_tests
        run: |
          xvfb-run pytest tests/unit_tests/gui/mainWmixin
