#
# v1.0, Michael Wuertenberger
#
name: unit_win

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  wid: 'mw4/gui/widgets/'
  uic: 'python -m PyQt5.uic.pyuic'
  ucc: 'python -m PyQt5.pyrcc_main'
  res: 'mw4/resource/'
  branch: 'master'

on:
  push:
    # Run this action on the trigger event when specific files are touched
    paths:
      - 'mw4/**'
      - 'tests/unit_tests/**'
      - 'setup.py'
      - 'tox.ini'
      - '.github/workflows/unit_win.yml'

jobs:
  build_widgets_resource:
    #
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{env.branch}}
          
      - name: build package
        uses: ./.github/actions/build_package

  run_tests_windows_1a:
    #
    needs: build_widgets_resource
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{env.branch}}
  
      - name: install package
        uses: ./.github/actions/setup_test_cov
  
      - name: running_unit_tests
        run: |
          pytest tests/unit_tests/zLoader --cov=mw4/ --cov-config=.coveragerc
          
      - name: rename_coveragefile
        run: mv .coverage c1a.dat
        
      - name: upload_coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: ./c1a.dat

  run_tests_windows_1b:
    #
    needs: build_widgets_resource
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{env.branch}}
  
      - name: install package
        uses: ./.github/actions/setup_test_cov
  
      - name: running_unit_tests
        run: |
          pytest tests/unit_tests/zUpdate --cov=mw4/ --cov-config=.coveragerc
          
      - name: rename_coveragefile
        run: mv .coverage c1b.dat
        
      - name: upload_coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: ./c1b.dat

  run_tests_windows_1c:
    #
    needs: build_widgets_resource
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{env.branch}}
  
      - name: install package
        uses: ./.github/actions/setup_test_cov
  
      - name: running_unit_tests
        run: |
          pytest tests/unit_tests/zMainApp --cov=mw4/ --cov-config=.coveragerc
          
      - name: rename_coveragefile
        run: mv .coverage c1c.dat
        
      - name: upload_coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: ./c1c.dat

  run_tests_windows_2a:
    #
    needs: build_widgets_resource
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{env.branch}}
  
      - name: install package
        uses: ./.github/actions/setup_test_cov
  
      - name: running_unit_tests
        run: |
          pytest tests/unit_tests/base --cov=mw4/ --cov-config=.coveragerc
          pytest tests/unit_tests/logic --cov-append --cov=mw4/ --cov-config=.coveragerc
          
      - name: rename_coveragefile
        run: mv .coverage c2a.dat
        
      - name: upload_coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: ./c2a.dat

  run_tests_windows_2b:
    #
    needs: build_widgets_resource
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{env.branch}}
  
      - name: install package
        uses: ./.github/actions/setup_test_cov
  
      - name: running_unit_tests
        run: |
          pytest tests/unit_tests/mountcontrol --cov=mw4/ --cov-config=.coveragerc
          pytest tests/unit_tests/indibase --cov-append --cov=mw4/ --cov-config=.coveragerc
          
      - name: rename_coveragefile
        run: mv .coverage c2b.dat
        
      - name: upload_coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: ./c2b.dat

  run_tests_windows_3a:
    #
    needs: build_widgets_resource
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{env.branch}}
  
      - name: install package
        uses: ./.github/actions/setup_test_cov
  
      - name: running_unit_tests
        run: |
          pytest tests/unit_tests/gui/mainWindow --cov=mw4/ --cov-config=.coveragerc
          pytest tests/unit_tests/gui/extWindows --cov-append --cov=mw4/ --cov-config=.coveragerc
          pytest tests/unit_tests/gui/utilities --cov-append --cov=mw4/ --cov-config=.coveragerc
          
      - name: rename_coveragefile
        run: mv .coverage c3a.dat
        
      - name: upload_coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: ./c3a.dat

  run_tests_windows_3b:
    #
    needs: build_widgets_resource
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{env.branch}}
  
      - name: install package
        uses: ./.github/actions/setup_test_cov
  
      - name: running_unit_tests
        run: |
          pytest tests/unit_tests/gui/extWindows --cov=mw4/ --cov-config=.coveragerc
          
      - name: rename_coveragefile
        run: mv .coverage c3b.dat
        
      - name: upload_coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: ./c3b.dat

  run_tests_windows_3c:
    #
    needs: build_widgets_resource
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{env.branch}}
  
      - name: install package
        uses: ./.github/actions/setup_test_cov
  
      - name: running_unit_tests
        run: |
          pytest tests/unit_tests/gui/utilities --cov=mw4/ --cov-config=.coveragerc
          
      - name: rename_coveragefile
        run: mv .coverage c3c.dat
        
      - name: upload_coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: ./c3c.dat

  run_tests_windows_4:
    #
    needs: build_widgets_resource
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{env.branch}}
  
      - name: install package
        uses: ./.github/actions/setup_test_cov
  
      - name: running_unit_tests
        run: |
          pytest tests/unit_tests/gui/mainWmixin1 --cov=mw4/ --cov-config=.coveragerc

      - name: rename_coveragefile
        run: mv .coverage c4.dat
        
      - name: upload_coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: ./c4.dat

  run_tests_windows_5:
    #
    needs: build_widgets_resource
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{env.branch}}
  
      - name: install package
        uses: ./.github/actions/setup_test_cov
  
      - name: running_unit_tests
        run: |
          pytest tests/unit_tests/gui/mainWmixin2 --cov=mw4/ --cov-config=.coveragerc

      - name: rename_coveragefile
        run: mv .coverage c5.dat
        
      - name: upload_coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: ./c5.dat

  run_tests_windows_6:
    #
    needs: build_widgets_resource
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{env.branch}}
  
      - name: install package
        uses: ./.github/actions/setup_test_cov
  
      - name: running_unit_tests
        run: |
          pytest tests/unit_tests/gui/mainWmixin3 --cov=mw4/ --cov-config=.coveragerc

      - name: rename_coveragefile
        run: mv .coverage c6.dat
        
      - name: upload_coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: ./c6.dat

  coverage:
    #
    needs: [ run_tests_windows_1a, run_tests_windows_1b,
             run_tests_windows_1c, run_tests_windows_2a,
             run_tests_windows_2b, run_tests_windows_3a,
             run_tests_windows_3b, run_tests_windows_3c,
             run_tests_windows_4, run_tests_windows_5,
             run_tests_windows_6]
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{env.branch}}
    
    - name: collecting_data
      uses: actions/download-artifact@v2
      with:
        name: coverage
        path: .
        
    - name: combining_data
      run: |
        dir
        python -m pip install coverage
        python -m coverage combine c1a.dat c1b.dat c1c.dat c2a.dat c2b.dat c3a.dat c3b.dat c3c.dat c4.dat c5.dat c6.dat
        python -m coverage xml

    - name: upload
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage.xml
        flags: unittests
        name: codecov-umbrella
        env_vars: OS,PYTHON
        override_branch: ${{env.branch}}
