#
# GitHub actions for running the unit test of the mountwizzard4 package
#
# v 1.0,  Michael Wuertenberger
#
name: wheels-test

on:
  push:
    # Run this action on the trigger event when specific files are touched
    paths:
      - '.github/workflows/wheels_test.yml'

jobs:
  build_job:
    # The host should always be linux
    runs-on: ubuntu-20.04
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    # Run steps on a matrix of 3 arch/distro combinations
    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu20.04

    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2.1.1
        name: build_artifact
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}

          # Not required, but speeds up builds
          githubToken: ${{ github.token }}

          # Mount the wheels directory as /artifacts in the container
          dockerRunArgs: |
            -v "${PWD}/support/2.0/wheels/${{ matrix.distro}}":/root/wheels

          # The shell to run commands with in the container
          shell: /bin/bash
          
          # Produce a binary artifact and place it in the mounted volume
          run: |
            ls -la /root/wheels/*.*
            
            if [ ! -f "/root/wheels/astropy-4.3.1-cp39-cp39-linux_aarch64.whl" ]
            then
              echo "astropy==4.3.1"
            fi
            
            if [ ! -f "/root/wheels/pyerfa-2.0.0-cp39-cp39m-linux_aarch64.whl" ]
            then
              echo "pyerfa==2.0.0"
            fi
            
            if [ ! -f "/root/wheels/sep-1.2.0-cp39-cp39-linux_aarch64.whl" ]
            then
              echo "sep==1.2.0"
            fi
            
            if [ ! -f "/root/wheels/sgp4-2.20-cp39-cp39-linux_aarch64.whl" ]
            then
              echo "sgp4==2.20"
            fi
            
            if [ ! -f "/root/wheels/PyQt5_sip-12.8.1-cp39-cp39-linux_aarch64.whl" ]
            then
              echo "pyqt5_sip==12.8.1"
            fi
            
            if [ ! -f "/root/wheels/PyQt5-5.15.4-cp36.cp37.cp38.cp39-abi3-manylinux2014_aarch64.whl" ]
            then
              echo "pyqt5==5.15.4"
            fi
